# Generated by Django 5.2.4 on 2025-08-13 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('A', 'Atrasada'), ('P', 'Pendente'), ('C', 'Concluída')], default='P', max_length=1)),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', max_length=6)),
                ('category', models.CharField(choices=[('T', 'Trabalho'), ('E', 'Estudos'), ('P', 'Pessoal')], default='P', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
