# Generated by Django 5.2.4 on 2025-08-07 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0002_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('T', 'Trabalho'), ('E', 'Estudos'), ('P', 'Pessoal')], default='P', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 8, 7)),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A', 'Atrasada'), ('P', 'Pendente'), ('C', 'Concluída')], default='P', max_length=1),
        ),
    ]
