# Generated by Django 5.2.4 on 2025-08-08 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_task_category_task_deadline_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 8, 8)),
        ),
    ]
