# Generated by Django 5.2.4 on 2025-08-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('A', 'admin'), ('C', 'Comun')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='username', max_length=10),
        ),
    ]
