# Generated by Django 5.2.4 on 2025-08-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
